### ISSUE TITLE
Google colab version

### ISSUE THREAD

**Issue by shadowzoom** [HENDRIX-ZT2/pyaudiorestoration#12]
Can somebody please make a google colab notebook for this project?

**Comment by HENDRIX-ZT2** [comment]
I don't use google colab or jupyter notebooks so idk. Not sure if that's even possible with the plethora of dependencies required for everything to work. But feel free to set one up if you can.

**Comment by forart** [comment]
You could can ask [MixLab](https://github.com/shirooo39/MiXLab) author @shirooo39 to integrate it in his project...
