### ISSUE TITLE
Memory issues with pyrespeeder

### ISSUE THREAD

**Issue by schtschenok** [HENDRIX-ZT2/pyaudiorestoration#14]
Hi! I've tried using pyrespeeder on some pretty big files, it worked surprisingly fast, though I believe that it's not flushing old FFT analysis results from the memory, since changing FFT settings for a couple of times (and waiting for pyrespeeder to reanalyze my file) quickly got me to memory usage of ~15GB.

**Comment by HENDRIX-ZT2** [comment]
Right the current behavior is to store previous resolutions so you can quickly toggle between them. Maybe there should be an option to toggle the automatic storage behavior, or a button to clear the storage if needed.

**Comment by schtschenok** [comment]
Something like this would be really great to have!

**Comment by HENDRIX-ZT2** [comment]
You'll want to try with the latest commit, which adds a button to clear the fft storage.

**Comment by schtschenok** [comment]
That's great, thank you, I'll try it!
