### ISSUE TITLE
Documentation for Spectral Temporal Alignment

### ISSUE THREAD

**Issue by RenaudZ** [HENDRIX-ZT2/pyaudiorestoration#18]
Hi,

I really like your amazing set of tools, it is the most useful I ever used to restore old bootlegs records.
Thank you very much for sharing this!

I'm very interested in your Spectral Temporal Alignement tool but I don't understand how to use it and I didn't find any explanations on the wiki pages.
Could you please post some documentation?

Thank you again!

**Comment by HENDRIX-ZT2** [comment]
I've added documentation to the wiki. Hope this helps! Happy bootlegging :)
