### ISSUE TITLE
[SUGGESTION] DEVINYL & GUI

### ISSUE THREAD

**Issue by forart** [HENDRIX-ZT2/pyaudiorestoration#27]
Hi there,
since both projects have similar goals, it would be great to establish some kind of cooperation with @matiaszanolli's one:
https://github.com/matiaszanolli/devinyl

We recently discovered [master_me](https://github.com/trummerschlunk/master_me) by @trummerschlunk wich shows a cool  GUI to "keep en eye" on:

![](https://raw.githubusercontent.com/trummerschlunk/master_me/master/img/screenshot-expert.png)

Hope that inspires !

**Comment by HENDRIX-ZT2** [comment]
Out of scope of this project, which is complex enough already as it is 😅
