### ISSUE TITLE
SO CLOSE....Please HELP!!!

### ISSUE THREAD

**Issue by aludra2020** [HENDRIX-ZT2/pyaudiorestoration#28]
Dear Mr. Hendrix-ZT2,

I think I am closer than I have been before to installing this great software...I have installed Microsoft C++ 14.0230260....Is that close enough to 14.0? If you have time could you look at the CMD readout and tell me what I'm doing wrong....Thank you so much for any help you can provide!

Warmest Regards,

Mike

C:\PY>python setup.py install
running install
running bdist_egg
running egg_info
writing pyaudiorestoration.egg-info\PKG-INFO
writing dependency_links to pyaudiorestoration.egg-info\dependency_links.txt
writing requirements to pyaudiorestoration.egg-info\requires.txt
writing top-level names to pyaudiorestoration.egg-info\top_level.txt
package init file 'pyaudiorestoration\__init__.py' not found (or not a regular file)
reading manifest file 'pyaudiorestoration.egg-info\SOURCES.txt'
writing manifest file 'pyaudiorestoration.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build\bdist.win32\egg
creating build\bdist.win32\egg\pyaudiorestoration
copying build\lib\pyaudiorestoration\decompressor_cmd.py -> build\bdist.win32\egg\pyaudiorestoration
copying build\lib\pyaudiorestoration\difeq_gui.py -> build\bdist.win32\egg\pyaudiorestoration
copying build\lib\pyaudiorestoration\dropouts_gui.py -> build\bdist.win32\egg\pyaudiorestoration
copying build\lib\pyaudiorestoration\expander_gui.py -> build\bdist.win32\egg\pyaudiorestoration
copying build\lib\pyaudiorestoration\hpss_gui.py -> build\bdist.win32\egg\pyaudiorestoration
copying build\lib\pyaudiorestoration\humspeed_gui.py -> build\bdist.win32\egg\pyaudiorestoration
copying build\lib\pyaudiorestoration\pypan_gui.py -> build\bdist.win32\egg\pyaudiorestoration
copying build\lib\pyaudiorestoration\pyrespeeder_cmd.py -> build\bdist.win32\egg\pyaudiorestoration
copying build\lib\pyaudiorestoration\pyrespeeder_gui.py -> build\bdist.win32\egg\pyaudiorestoration
copying build\lib\pyaudiorestoration\pytapesynch_gui.py -> build\bdist.win32\egg\pyaudiorestoration
byte-compiling build\bdist.win32\egg\pyaudiorestoration\decompressor_cmd.py to decompressor_cmd.cpython-38.pyc
byte-compiling build\bdist.win32\egg\pyaudiorestoration\difeq_gui.py to difeq_gui.cpython-38.pyc
byte-compiling build\bdist.win32\egg\pyaudiorestoration\dropouts_gui.py to dropouts_gui.cpython-38.pyc
byte-compiling build\bdist.win32\egg\pyaudiorestoration\expander_gui.py to expander_gui.cpython-38.pyc
byte-compiling build\bdist.win32\egg\pyaudiorestoration\hpss_gui.py to hpss_gui.cpython-38.pyc
byte-compiling build\bdist.win32\egg\pyaudiorestoration\humspeed_gui.py to humspeed_gui.cpython-38.pyc
byte-compiling build\bdist.win32\egg\pyaudiorestoration\pypan_gui.py to pypan_gui.cpython-38.pyc
byte-compiling build\bdist.win32\egg\pyaudiorestoration\pyrespeeder_cmd.py to pyrespeeder_cmd.cpython-38.pyc
byte-compiling build\bdist.win32\egg\pyaudiorestoration\pyrespeeder_gui.py to pyrespeeder_gui.cpython-38.pyc
byte-compiling build\bdist.win32\egg\pyaudiorestoration\pytapesynch_gui.py to pytapesynch_gui.cpython-38.pyc
creating build\bdist.win32\egg\EGG-INFO
copying pyaudiorestoration.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying pyaudiorestoration.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying pyaudiorestoration.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying pyaudiorestoration.egg-info\requires.txt -> build\bdist.win32\egg\EGG-INFO
copying pyaudiorestoration.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\pyaudiorestoration-1.0-py3.8.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing pyaudiorestoration-1.0-py3.8.egg
Removing c:\py\lib\site-packages\pyaudiorestoration-1.0-py3.8.egg
Copying pyaudiorestoration-1.0-py3.8.egg to c:\py\lib\site-packages
pyaudiorestoration 1.0 is already the active version in easy-install.pth

Installed c:\py\lib\site-packages\pyaudiorestoration-1.0-py3.8.egg
Processing dependencies for pyaudiorestoration==1.0
Searching for pyfftw
Reading https://pypi.org/simple/pyfftw/
Downloading https://files.pythonhosted.org/packages/18/a1/5eb99c183af0a49bf632fed3260a6cad3f7978bb19fd661a573d3728a986/pyFFTW-0.13.0.tar.gz#sha256=da85102405c0bd95d57eb19e99b01a0729d8406cb204c3900894b873784253da
Best match: pyFFTW 0.13.0
Processing pyFFTW-0.13.0.tar.gz
Writing C:\Users\mike\AppData\Local\Temp\easy_install-t5md1op7\pyFFTW-0.13.0\setup.cfg
Running pyFFTW-0.13.0\setup.py -q bdist_egg --dist-dir C:\Users\mike\AppData\Local\Temp\easy_install-t5md1op7\pyFFTW-0.13.0\egg-dist-tmp-2aw8astm
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
warning: no files found matching 'CHANGELOG.md'
warning: no files found matching 'README.rst'
warning: no files found matching 'test\*.py'
no previously-included directories found matching 'docs\_build'
no previously-included directories found matching 'build'
no previously-included directories found matching '*\__pycache__'
warning: no previously-included files matching '*.py[cod]' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.dylib' found anywhere in distribution
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.bak' found anywhere in distribution
warning: no previously-included files matching '*.swp' found anywhere in distribution
UPDATING build\lib.win32-3.8\pyfftw/_version.py
set build\lib.win32-3.8\pyfftw/_version.py to '0.13.0'
DEBUG:__main__:Link FFTW dynamically
DEBUG:__main__:Compiler include_dirs: ['C:\\PY\\include', 'C:\\PY\\include']
error: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

**Comment by HENDRIX-ZT2** [comment]
No need for you to compile pyfftw yourself - see this bit from the readme:
[pyFFTW](https://github.com/pyFFTW/pyFFTW) (optional speedup) Note for python 3.6 users on windows - to install pyFFTW, download the correct .whl file from Download (scroll down!) and install it with pip install PATH_TO_FILE.whl.
